### ISSUE TITLE
Parsing and converting MathJax

### ISSUE THREAD

**Issue by mmahmoudian** [laurent22/joplin-turndown#1]
The current version apparently does not support MathJax (which is the most common form of putting a mathematical formula on webpages. I asked turndown developers to implement its support but they said this is better to be done here:

https://github.com/domchristie/turndown/issues/260

The following suggestion seems to be logically valid to quickly have the support:

https://github.com/domchristie/turndown/issues/260#issuecomment-431849389

**Comment by laurent22** [comment]
Fixed in 456d585db54f6d667970b9514bd697f57b92301c
